### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by marcofuentes05** [Raja0sama/rn-foreground-service#84]
Hello,

I have been using this library for the past six months without any major problem. Me and my team love it! However, I just updated my RN to version 0.73.1 (we were using 0.71.3) and now I can't build the app because of a bug in this ligbrary: 
```
node_modules/@supersami/rn-foreground-service/android/src/main/java/com/supersami/foregroundservice/NotificationHelper.java:144: error: cannot find symbol
            notificationBuilder.addAction(R.drawable.redbox_top_border_background, bundle.getString("buttonText", "Button"), pendingBtnIntent);
                                           ^
  symbol:   variable drawable
  location: class R
```

I don't have a lot of knowledge in android development, but examining the file it seems the error is related to the rendering of buttons in the notification showed when the process is active:

<img width="900" alt="image" src="https://github.com/Raja0sama/rn-foreground-service/assets/40815025/5f891f12-92fe-41a4-86fa-6212ddca2a6c">

Just commenting out lines 144 and 148 makes the error dissappear. I imagine this won't break anything in my app since we don't use buttons in our notifications. But I wonder what caused this issue? And how can I solve it _the good way_?

**Comment by fredericosafebox** [comment]
I am facing the same issue.

**Comment by fredericosafebox** [comment]
I've never had this file. I've just checked my  project's previous version, which was built with RN 0.70.6, and found no `drawable.redbox_top_border_background`. Lines 144 and 148 that @marcofuentes05 posted were also present by the time, but after I upgraded my RN to 0.73.2 I started having this problem. I wonder what I am trully missing here

**Comment by GopalVerma1303** [comment]
I am also facing the same issue. Had anyone solved it? Or would like to suggest any "quick-fix".
<img width="1552" alt="Screenshot 2024-01-21 at 2 53 12 PM" src="https://github.com/Raja0sama/rn-foreground-service/assets/67120469/f8084c00-8c14-4759-b7ae-17c7462c6c80">

**Comment by fredericosafebox** [comment]
I think that for some reason the class `R` is not accessible anymore. Maybe related to the RN version (which in my case was upgraded from 0.70.6 to 0.73), because my `drawable` folder structure remains the same.

**Comment by fredericosafebox** [comment]
Maybe a solution is to use the new Notification.Builder addAction, which was added in API level 20, since it does not require an Icon as parameter. Or pass a valid Icon from R class to ensure it will not break.

**Comment by GopalVerma1303** [comment]
Thanks! I will try.

**Comment by Pankajjajra** [comment]
I have found a solution for this.

just change -

R.drawable.redbox_top_border_background

to

com.facebook.react.R.drawable.redbox_top_border_background

**Comment by barokatu** [comment]
for you guys that face same error after upgrade the RN version to 0.74.1
you can use this library

https://www.npmjs.com/package/@barokatu/rn-foreground-service


it's actually same, but the error already fixed by change
`R.drawable.redbox_top_border_background` to `com.facebook.react.R.drawable.redbox_top_border_background`

as @Pankajjajra mention on his comment
